# Generated by Django 4.2.4 on 2024-01-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
