# Generated by Django 4.2.4 on 2024-01-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ace_finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
