# Generated by Django 4.2.4 on 2024-01-18 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ace_finance', '0002_transactions_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_id', models.CharField(max_length=100)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_transactions', to='ace_finance.user_account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_transactions', to='ace_finance.user_account')),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
