# Generated by Django 4.2.4 on 2024-01-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_finance', '0003_transaction_user_delete_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_user',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='accountNumber',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
