# Generated by Django 4.2.4 on 2024-01-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_finance', '0004_alter_transaction_user_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='balance',
            field=models.BigIntegerField(default=1000),
        ),
    ]
