# Generated by Django 4.2.4 on 2024-01-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ace_finance", "0004_alter_transaction_user_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_account",
            name="balance",
            field=models.BigIntegerField(default=1000),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_status",
                    models.CharField(
                        choices=[("read", "Read"), ("not_read", "Not Read")],
                        default="not_read",
                        max_length=100,
                    ),
                ),
                ("notification_title", models.TextField()),
                ("notification_details", models.TextField()),
                (
                    "noti_user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="ace_finance.user_account",
                    ),
                ),
            ],
        ),
    ]
