# Generated by Django 4.2.4 on 2024-01-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ace_finance', '0005_alter_user_account_balance'),
        ('ace_finance', '0005_alter_user_account_balance_notification'),
    ]

    operations = [
    ]
