# Generated by Django 4.2.4 on 2023-10-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_shelf_pagesnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_shelf',
            name='pagesNumber',
            field=models.IntegerField(default=0),
        ),
    ]
