# Generated by Django 4.2.4 on 2023-10-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_folder_names_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Folder_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='folders',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder_Names',
        ),
        migrations.DeleteModel(
            name='Folders',
        ),
        migrations.AddField(
            model_name='folder',
            name='folder',
            field=models.ManyToManyField(related_name='content', to='books.folder_name'),
        ),
    ]
