# Generated by Django 4.2.4 on 2023-10-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_folder_folder_name_remove_folders_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='books',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.book_shelf'),
        ),
    ]
