# Generated by Django 4.2.4 on 2023-10-24 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_reviews',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
