# Generated by Django 4.2.4 on 2023-10-26 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0014_publicshelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicshelf',
            name='shelf',
        ),
        migrations.AlterField(
            model_name='publicshelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public', to=settings.AUTH_USER_MODEL),
        ),
    ]
