# Generated by Django 4.2.4 on 2024-01-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_reviews_bookid_alter_book_reviews_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_reviews',
            name='bookId',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book_reviews',
            name='content',
            field=models.TextField(),
        ),
    ]
