# Generated by Django 4.2.4 on 2024-01-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_reviews_bookid_alter_book_reviews_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_reviews',
            name='bookId',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book_reviews',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book_reviews',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book_shelf',
            name='authors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book_shelf',
            name='book_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book_shelf',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book_shelf',
            name='imageLink',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book_shelf',
            name='publishedDate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book_shelf',
            name='publisher',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book_shelf',
            name='status',
            field=models.TextField(choices=[('not_started', 'Not Started'), ('reading', 'Currently Reading'), ('finished', 'Finished Reading')], default='not_started', max_length=50),
        ),
        migrations.AlterField(
            model_name='book_shelf',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='collection_name',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.TextField(),
        ),
    ]
